version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3.7-management"
    hostname: "${SLAVE_NAME}"
    environment:
      - RABBITMQ_ERLANG_COOKIE=key_secrets
      - RABBITMQ_NODENAME=${SLAVE_NAME}
    ports:
      - "15672:15672"
      - "5672:5672"
      - "4369:4369"
      - "25672:25672"
    labels:
      NAME: "${SLAVE_NAME}"
    extra_hosts:
      - "rabbitmaster:${MASTER_IP}"
    volumes:
      - "./rabbitmq:/etc/rabbitmq/rabbitmq.config"
      - "./definitions.json:/etc/rabbitmq/definitions.json"
      - "./slave_join.sh:/slave_join.sh"
      - "rabbitslave:/var/lib/rabbitmq"
    tty: true
volumes:
  rabbitslave:
    driver: local
