version: '3'

services:

  rabbitmq:
    image: "rabbitmq:3.7-management"
    hostname: "rabbit"
    environment: 
      - RABBITMQ_ERLANG_COOKIE=keysecrets
      - RABBITMQ_NODENAME=rabbit1
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - "./rabbitmq:/etc/rabbitmq/rabbitmq.config"
      - "./definitions.json:/etc/rabbitmq/definitions.json"