version: '3'

services:

  rabbitmq:
    image: "rabbitmq:3.10-management"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    hostname: "rabbitmaster"
    environment: 
      - RABBITMQ_ERLANG_COOKIE=key_secrets
      - RABBITMQ_NODENAME=rabbitmaster
    ports:
      - "15672:15672"
      - "5672:5672"
      - "4369:4369"
      - "25672:25672"
    tty: true
    labels:
      NAME: "rabbitmqmaster"
    extra_hosts:
      - "rabbitmaster:192.168.218.129" # clone1
      - "rabbitslave1:192.168.218.130" # clone2
      - "rabbitslave2:192.168.218.131" # clone3
    volumes:
      - "./rabbitmq:/etc/rabbitmq/rabbitmq.config"
      - "./definitions.json:/etc/rabbitmq/definitions.json"
      - "rabbitmaster:/var/lib/rabbitmq"
volumes:
  rabbitmaster:
    driver: local