version: '3'

services:

  rabbitmq:
    image: "rabbitmq:3.7-management"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    hostname: "rabbitmaster"
    environment: 
      - RABBITMQ_ERLANG_COOKIE=key_secrets
      - RABBITMQ_NODENAME=rabbitmaster
    ports:
      - "15672:15672"
      - "5672:5672"
      - "4369:4369"
      - "25672:25672"
    tty: true
    labels:
      NAME: "rabbitmqmaster"
    volumes:
      - "./rabbitmq:/etc/rabbitmq/rabbitmq.config"
      - "./definitions.json:/etc/rabbitmq/definitions.json"
      - "rabbitmaster:/var/lib/rabbitmq"
volumes:
  rabbitmaster:
    driver: local