version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3.7-management"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    hostname: "${SLAVE_NAME}"
    environment:
      - RABBITMQ_ERLANG_COOKIE=key_secrets
      - RABBITMQ_NODENAME=${SLAVE_NAME}
    ports:
      - "15672:15672"
      - "5672:5672"
      - "4369:4369"
      - "25672:25672"
    labels:
      NAME: "${SLAVE_NAME}"
    extra_hosts:
      - "rabbitmaster:${MASTER_IP}" #clone1
      - "rabbitslave1:192.168.218.130" #clone2
      - "rabbitslave2:192.168.218.131" #clone3
    volumes:
      - "./rabbitmq:/etc/rabbitmq/rabbitmq.config"
      - "./definitions.json:/etc/rabbitmq/definitions.json"
      - "./slave_join.sh:/slave_join.sh"
      - "rabbitslave:/var/lib/rabbitmq"
    tty: true
volumes:
  rabbitslave:
    driver: local
