version: '3'

services:

  rabbitmq:
    build:
     context: .
     args:
      - MASTER_IP=192.168.1.127
    hostname: "rabbitslave"
    environment: 
      - RABBITMQ_ERLANG_COOKIE=key_secrets
      - RABBITMQ_NODENAME=rabbitslave
    ports:
      - "15672:15672"
      - "5672:5672"
      - "4369:4369"
      - "25672:25672"
    labels:
      NAME: "rabbitmqslave"
    volumes:
      - "./rabbitmq:/etc/rabbitmq/rabbitmq.config"
      - "./definitions.json:/etc/rabbitmq/definitions.json"
      - "./slave_join.sh:/usr/local/bin/slave_join.sh"
      - "./add_hosts.sh:/usr/local/bin/add_hosts.sh"
      - "/opt/rabbitmq_data_slave:/var/lib/rabbitmq/mnesia/rabbitslave"
    command: 
      - slave_join.sh