version: '3'

services:
  rabbitmq:
    build:
     context: .
    hostname: "${SLAVE_NAME}"
    environment:
      - RABBITMQ_ERLANG_COOKIE=key_secrets
      - RABBITMQ_NODENAME=${SLAVE_NAME}
    ports:
      - "15672:15672"
      - "5672:5672"
      - "4369:4369"
      - "25672:25672"
    labels:
      NAME: "${SLAVE_NAME}"
    extra_hosts:
      - "rabbitmaster:${MASTER_IP}"
    volumes:
      - "./rabbitmq:/etc/rabbitmq/rabbitmq.config"
      - "./definitions.json:/etc/rabbitmq/definitions.json"
      - "./slave_join.sh:/slave_join.sh"
      - "/opt/rabbitmq_data_slave:/var/lib/rabbitmq/mnesia/rabbitslave"
    tty: true
    stdin_open: true
